import { Post, Profile } from '@/types/post';

export const founderPosts: Post[] = [
  {
    id: 'f1',
    authorName: 'Vikram Reddy',
    handle: 'vikram_builds',
    title: 'Early launch sprint update',
    excerpt: 'Hit a small but vital milestone. Completed first user onboarding flow and shipped email verification. This was a blocker for growth.',
    xpAwarded: 25,
    streakDays: 9,
    level: 12,
    tags: ['product', 'onboarding'],
    createdAt: '2025-01-15',
    isMock: true,
    avatarUrl: 'https://i.pravatar.cc/150?img=12',
  },
  {
    id: 'f2',
    authorName: 'Ananya Sharma',
    handle: 'ananya_sharma',
    title: 'Prototype to usable',
    excerpt: 'Turned an internal prototype into a testable user flow. Two founders tested it and we learned three improvements to make next week.',
    xpAwarded: 40,
    streakDays: 15,
    level: 15,
    tags: ['prototype', 'testing'],
    createdAt: '2025-01-14',
    isMock: true,
    avatarUrl: 'https://i.pravatar.cc/150?img=45',
  },
  {
    id: 'f3',
    authorName: 'Rohan Gupta',
    handle: 'rohan_g',
    title: 'Revenue experiment',
    excerpt: 'Launched a small pricing experiment with ten users. Early signals are promising. Revenue per user is positive but sample is small.',
    xpAwarded: 60,
    streakDays: 6,
    level: 10,
    tags: ['revenue', 'experiment'],
    createdAt: '2025-01-13',
    isMock: true,
    avatarUrl: 'https://i.pravatar.cc/150?img=33',
  },
  {
    id: 'f4',
    authorName: 'Kavya Patel',
    handle: 'kavya_builds',
    title: 'Verified signal earned',
    excerpt: 'Completed third integration with payment provider and obtained verified signal. Badge added to profile. This reduces investor friction.',
    xpAwarded: 100,
    streakDays: 24,
    level: 13,
    tags: ['verified signal'],
    createdAt: '2025-01-12',
    isMock: true,
    avatarUrl: 'https://i.pravatar.cc/150?img=47',
  },
  {
    id: 'f5',
    authorName: 'Aditya Kumar',
    handle: 'aditya_k',
    title: 'First paying customer',
    excerpt: 'Closed our first paying customer today after 47 cold emails. Small win but validation that people will pay for this solution.',
    xpAwarded: 80,
    streakDays: 31,
    level: 14,
    tags: ['traction', 'revenue'],
    createdAt: '2025-01-11',
    isMock: true,
    avatarUrl: 'https://i.pravatar.cc/150?img=51',
  },
  {
    id: 'f6',
    authorName: 'Priya Singh',
    handle: 'priya_s',
    title: 'Product iteration',
    excerpt: 'Shipped three feature improvements based on user feedback. Response time down by 40%. Users notice the difference.',
    xpAwarded: 55,
    streakDays: 18,
    level: 11,
    tags: ['product', 'iteration'],
    createdAt: '2025-01-10',
    isMock: true,
    avatarUrl: 'https://i.pravatar.cc/150?img=29',
  },
];

export const investorPosts: Post[] = [
  {
    id: 'i1',
    authorName: 'Nikhil Rao',
    handle: 'nikhil_invests',
    title: 'Founders every investor should watch',
    excerpt: 'We identified three founders who improved their onboarding conversion by 20% in two weeks. This signals strong execution and product sense.',
    xpAwarded: 30,
    streakDays: 12,
    level: 8,
    tags: ['deal flow'],
    createdAt: '2025-01-15',
    isMock: true,
    avatarUrl: 'https://i.pravatar.cc/150?img=13',
  },
  {
    id: 'i2',
    authorName: 'Meera Deshmukh',
    handle: 'meera_vc',
    title: 'Early traction snapshot',
    excerpt: 'Small cohort experiment shows 15 percent weekly retention. Continuing to iterate on onboarding and pricing.',
    xpAwarded: 50,
    streakDays: 7,
    level: 9,
    tags: ['retention', 'metrics'],
    createdAt: '2025-01-14',
    isMock: true,
    avatarUrl: 'https://i.pravatar.cc/150?img=32',
  },
  {
    id: 'i3',
    authorName: 'Arjun Malhotra',
    handle: 'arjun_m',
    title: 'Verified integration reduces friction',
    excerpt: 'Payment provider integration is live. Verified signal added. Lowered friction for first time payers.',
    xpAwarded: 80,
    streakDays: 20,
    level: 11,
    tags: ['verified signal'],
    createdAt: '2025-01-13',
    isMock: true,
    avatarUrl: 'https://i.pravatar.cc/150?img=68',
  },
  {
    id: 'i4',
    authorName: 'Sanya Iyer',
    handle: 'sanya_invests',
    title: 'Founder discipline visible',
    excerpt: 'Nightly shipping streaks and consistent weekly updates show high execution discipline. This predicts long term durability.',
    xpAwarded: 45,
    streakDays: 18,
    level: 10,
    tags: ['execution', 'discipline'],
    createdAt: '2025-01-12',
    isMock: true,
    avatarUrl: 'https://i.pravatar.cc/150?img=28',
  },
];

export const sampleProfiles: Profile[] = [
  {
    name: 'Karthik Venkat',
    handle: 'karthik_v',
    level: 16,
    xp: 14250,
    streak: 78,
    role: 'founder',
    avatarUrl: 'https://i.pravatar.cc/150?img=60',
  },
  {
    name: 'Isha Verma',
    handle: 'isha_verma',
    level: 11,
    xp: 9100,
    streak: 42,
    role: 'founder',
    avatarUrl: 'https://i.pravatar.cc/150?img=44',
  },
  {
    name: 'Aarav Nambiar',
    handle: 'aarav_n',
    level: 19,
    xp: 18900,
    streak: 112,
    role: 'founder',
    avatarUrl: 'https://i.pravatar.cc/150?img=57',
  },
];

export const mockPosts: Post[] = [...founderPosts, ...investorPosts];
